src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"email"}, message="There is already an account with this e-mail address")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    public const ROLES = array(
        'ROLE_ADMIN' => 'ROLE_ADMIN',
        'ROLE_SUPER_ADMIN' => 'ROLE_SUPER_ADMIN',
        'ROLE_API' => 'ROLE_API',
        'ROLE_HOUSEKEEPINGBOOK' => 'ROLE_HOUSEKEEPINGBOOK',
        'ROLE_SUPPLIES' => 'ROLE_SUPPLIES',
    );

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    #[Assert\NotBlank]
    #[Assert\Email]
    private $email;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToOne(targetEntity=UserProfile::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $userProfile;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=ApiToken::class, mappedBy="user", orphanRemoval=true)
     */
    private $apiTokens;

    /**
     * @ORM\OneToMany(targetEntity=HouseholdUser::class, mappedBy="user", orphanRemoval=true)
     */
    private $householdUsers;

    public function __construct()
    {
        $this->apiTokens = new ArrayCollection();
        $this->householdUsers = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->email;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        //TODO: remove getUsername() and only use getUserIdentifier()
        return $this->getUserIdentifier();
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getUserProfile(): ?UserProfile
    {
        return $this->userProfile;
    }

    public function setUserProfile(UserProfile $userProfile): self
    {
        // set the owning side of the relation if necessary
        if ($userProfile->getUser() !== $this) {
            $userProfile->setUser($this);
        }

        $this->userProfile = $userProfile;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->createdAt = new DateTime();
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new DateTime();
    }

    /**
     * @return Collection
     */
    public function getApiTokens(): Collection
    {
        return $this->apiTokens;
    }

    public function addApiToken(ApiToken $apiToken): self
    {
        if (!$this->apiTokens->contains($apiToken)) {
            $this->apiTokens[] = $apiToken;
            $apiToken->setUser($this);
        }

        return $this;
    }

    public function removeApiToken(ApiToken $apiToken): self
    {
        if ($this->apiTokens->removeElement($apiToken)) {
            // set the owning side to null (unless already changed)
            if ($apiToken->getUser() === $this) {
                $apiToken->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection
     */
    public function getHouseholdUsers(): Collection
    {
        return $this->householdUsers;
    }

    public function addHouseholdUser(HouseholdUser $householdUser): self
    {
        if (!$this->householdUsers->contains($householdUser)) {
            $this->householdUsers[] = $householdUser;
            $householdUser->setUser($this);
        }

        return $this;
    }

    public function removeHouseholdUser(HouseholdUser $householdUser): self
    {
        if ($this->householdUsers->removeElement($householdUser)) {
            // set the owning side to null (unless already changed)
            if ($householdUser->getUser() === $this) {
                $householdUser->setUser(null);
            }
        }

        return $this;
    }
}

src/Entity/UserProfile.php
<?php

namespace App\Entity;

use App\Repository\UserProfileRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserProfileRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class UserProfile
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="userProfile", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $forenames;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $locale;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getForenames(): ?string
    {
        return $this->forenames;
    }

    public function setForenames(string $forenames): self
    {
        $this->forenames = $forenames;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getNaturalName(): string
    {
        return $this->forenames . ' ' . $this->surname;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->createdAt = new DateTime();
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new DateTime();
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }
}

templates/theme/_page_messages.html.twig
<div id="toasts"></div>

{% if error is defined and error %}
    <div class="alert alert-danger">
        {{ error.messageKey|trans(error.messageData, 'security') }}
    </div>
{% endif %}

{% for label, messages in app.flashes %}
    {% for message in messages %}
        {% if label == "info" %}
            <div class="alert alert-info alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h5><i class="icon fas fa-info"></i> {{ 'app.information'|trans|u.title }}</h5>
                {{ message|trans }}
            </div>
        {% elseif label == "success" %}
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h5><i class="icon fas fa-check"></i> {{ 'app.success'|trans|u.title }}</h5>
                {{ message|trans }}
            </div>
        {% elseif label == "warning" %}
            <div class="alert alert-warning alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> {{ 'app.warning'|trans|u.title }}</h5>
                {{ message|trans }}
            </div>
        {% elseif label == "error" %}
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h5><i class="icon fas fa-ban"></i> {{ 'app.error'|trans|u.title }}</h5>
                {{ message|trans }}
            </div>
        {% endif %}
    {% endfor %}
{% endfor %}

templates/theme/_toasts.html.twig
<script type="text/javascript">
    {% for label, messages in app.flashes %}
    {% for message in messages %}
    $(document).Toasts('create', {
        {#title: '{{ label }}',#}
        class: 'bg-{{ label }}',
        body: '{{ message }}',
        autohide: true,
        delay: 3000,
        close: true,
        icon: 'fas fa-exclamation-triangle',
        position: 'topRight',
    });
    {% endfor %}
    {% endfor %}
</script>

templates/theme/base-datatables.html.twig
{% extends 'theme/base.html.twig' %}

{% block stylesheets_pre %}
    {{ parent() }}

    {{ encore_entry_link_tags('datatables') }}
{% endblock stylesheets_pre %}

{% block javascripts_pre %}
    {{ parent() }}

    {{ encore_entry_script_tags('datatables') }}
{% endblock javascripts_pre %}

templates/theme/base.html.twig
{% extends 'theme/blank_admin-lte-3_original.html.twig' %}

{% block title %}
    <title>{% if pageTitle is defined %}{{ pageTitle|trans }} - {% endif %}{{ siteName }}</title>
{% endblock title %}


{% block stylesheets_pre %}
    {{ encore_entry_link_tags('app') }}
{% endblock stylesheets_pre %}


{% block stylesheets %}
    {{ encore_entry_link_tags('omh') }}
{% endblock stylesheets %}


{% block stylesheets_post %}
    {{ encore_entry_link_tags('zzz') }}
{% endblock stylesheets_post %}


{% block body_tag %}
    <body class="hold-transition sidebar-mini layout-navbar-fixed">
{% endblock body_tag %}


{#
    Using text-sm in the body tag leads to a gap at the bottom of the sidebar.
    As a workaround, text-sm is instead set on navbar_tag, sidebar_tag and main_content_tag
#}

{% block navbar_tag %}
    <nav class="main-header navbar navbar-expand navbar-white navbar-light text-sm">
{% endblock navbar_tag %}


{% block sidebar_logo %}
    <!-- Brand Logo -->
    <a href="{{ path('homepage') }}" class="brand-link">
        <img src="{{ asset('build/images/OhMyHousehold_166x166.png') }}" alt="{{ siteName}} Logo" class="brand-image img-circle elevation-3" style="opacity: .8; width: 32px;">
        <span class="brand-text font-weight-light">{{ siteName }}</span>
    </a>
{% endblock sidebar_logo %}


{% block sidebar_user %}
{% endblock sidebar_user %}


{% block sidebar_search %}
{% endblock sidebar_search %}


{% block sidebar_nav_tag %}
    <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
{% endblock sidebar_nav_tag %}

{% block sidebar_links %}
    {% include '_sidebar_links.html.twig' %}
{% endblock %}


{% block navbar_left_items %}
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{{ path('homepage') }}" class="nav-link">Home</a>
    </li>
    {% if is_granted('ROLE_SUPER_ADMIN') %}
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{ path('app_admin_index') }}" class="nav-link">Admin</a>
        </li>
    {% endif %}
    {% if is_granted('ROLE_HOUSEKEEPINGBOOK') %}
        <li class="nav-item dropdown dropdown-hover">
            <a class="nav-link" href="{{ path('housekeepingbook_report_periodical_current') }}">
                {{ 'housekeeping_book'|trans|title }}
            </a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow" style="left: 0px; right: inherit;">
                {% if is_granted('createDepositTransaction', current_household) %}
                    <li><a href="{{ path('housekeepingbook_deposit_transaction_new') }}" class="dropdown-item">
                            <i class="text-green far fa-smile mr-2"></i>{{ 'add_deposit_transaction'|trans }}</a></li>
                {% endif %}
                {% if is_granted('createWithdrawalTransaction', current_household) %}
                    <li><a href="{{ path('housekeepingbook_withdrawal_transaction_new') }}" class="dropdown-item">
                            <i class="text-red far fa-frown mr-2"></i>{{ 'add_withdrawal_transaction'|trans }}</a></li>
                {% endif %}
                {% if is_granted('createTransferTransaction', current_household) %}
                    <li><a href="{{ path('housekeepingbook_transfer_transaction_new') }}" class="dropdown-item">
                            <i class="far fa-meh mr-2"></i>{{ 'add_transfer_transaction'|trans }}</a></li>
                {% endif %}
            </ul>
        </li>


    {% endif %}
    {% if is_granted('ROLE_SUPPLIES') %}
        <li class="nav-item dropdown dropdown-hover">
            <a class="nav-link" href="#" id="dropdown-language" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ 'supply_management'|trans|title }}
            </a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow" style="left: 0px; right: inherit;">
                {% if is_granted('checkoutSuppliesItem', current_household) %}
                    <li><a href="{{ path('supplies_item_checkout_form') }}" class="dropdown-item">{{ 'supplies_checkout'|trans }}</a></li>
                {% endif %}
                {% if is_granted('createSuppliesItem', current_household) %}
                    <li><a href="{{ path('supplies_item_new') }}" class="dropdown-item">{{ 'add_supply_items'|trans }}</a></li>
                {% endif %}
            </ul>
        </li>
    {% endif %}
{% endblock navbar_left_items %}


{% block navbar_search %}
{% endblock navbar_search %}


{% block masquerade %}
    {% if is_granted('IS_IMPERSONATOR') %}
        <div class="red text-red">
            <i class="fas fa-exclamation-triangle"></i>
            {% trans with {'name': app.user.username} %}app.currently-masqueraded-as{% endtrans %}
            <a class="btn btn-outline-danger btn-sm" style="color: red;" href="{{ impersonation_exit_url() }}">{{ 'app.end'|trans }}</a>
        </div>
    {% endif %}
{% endblock masquerade %}


{% block navbar_notifications_dropdown %}
    {{ include('supplies/_navbar_notifications_expiring_supply_items.html.twig') }}
    {{ include('supplies/_navbar_notifications_running_low_supplies.html.twig') }}
{% endblock navbar_notifications_dropdown %}


{% block navbar_control_fullscreen_button %}
{% endblock navbar_control_fullscreen_button %}


{% block navbar_messages_dropdown %}
    {% if not is_granted('ROLE_USER') %}
    <li class="nav-item dropdown">
        <a class="nav-link" href="#" id="dropdown-language" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="text-primary fas fa-language ml-1"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-language">
            {% for key, value in supportedLocales %}
                <a class="dropdown-item" href="{{ path('app_user_locale', {_locale: key}) }}">
                    {{ value|u.title }}
                </a>
            {% endfor %}
        </div>
    </li>
    {% endif %}
{% endblock navbar_messages_dropdown %}


{% block navbar_control_sidebar_button %}
{% endblock navbar_control_sidebar_button %}


{% block login_logout_button %}
    {% if is_granted('ROLE_USER') %}
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                {{ app.user.userProfile.naturalName }} <i class="text-success far fa-user fa-2x ml-1"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <div class="media-body">
{#                            <h3 class="dropdown-item-title">#}
{#                                <span class="text-sm">User settings</span>#}
{#                            </h3>#}
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
{#                <div class="dropdown-divider"></div>#}
                <div class="dropdown-footer">
                    <a  href="{{ path('app_user_settings') }}" class="btn btn-primary btn-sm mr-3">{{ 'app.settings'|trans }}</a>
                    <a  href="{{ logout_path() }}" class="btn btn-danger btn-sm ml-3">{{ 'app.sign-out'|trans|u.title }}</a>
                </div>

            </div>
        </li>

    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{{ path('app_user_register') }}">
                <i class="fas fa-user-plus mr-1"></i> {{ 'app.register'|trans|u.title }}
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ path('app_user_login') }}">
                <i class="fas fa-sign-in-alt mr-1"></i> {{ 'app.sign-in'|trans|u.title }}
            </a>
        </li>
    {% endif %}
{% endblock login_logout_button %}


{% block content_page_header %}{% endblock content_page_header %}


{% block page_messages %}
    {{ include('theme/_page_messages.html.twig') }}
{% endblock page_messages %}


{% block main_content_tag %}
    <section class="content text-sm">
{% endblock main_content_tag %}


{% block page_body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-lg">
                                <h3 class="card-title page-title">{% block page_header %}{{ pageTitle|trans }}{% endblock page_header %}</h3>
                            </div>
                            <div class="col-lg text-right">
                                {% block page_header_buttons %}{% endblock page_header_buttons %}
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        {% block page_content %}
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="card">
                                        <div class="card-body">
                                            <h5 class="card-title">Card title</h5>

                                            <p class="card-text">
                                                Some quick example text to build on the card title and make up the bulk of the card's
                                                content.
                                            </p>

                                            <a href="#" class="card-link">Card link</a>
                                            <a href="#" class="card-link">Another link</a>
                                        </div>
                                    </div><!-- /.card -->

                                    <div class="card card-primary card-outline">
                                        <div class="card-body">
                                            <h5 class="card-title">Card title</h5>

                                            <p class="card-text">
                                                Some quick example text to build on the card title and make up the bulk of the card's
                                                content.
                                            </p>

                                            <a href="#" class="card-link">Card link</a>
                                            <a href="#" class="card-link">Another link</a>
                                        </div>
                                    </div><!-- /.card -->
                                </div>
                                <!-- /.col-md-8 -->

                                <div class="col-md-4">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5 class="m-0">Featured</h5>
                                        </div>
                                        <div class="card-body">
                                            <h6 class="card-title">Special title treatment</h6>

                                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                            <a href="#" class="btn btn-primary">Go somewhere</a>
                                        </div>
                                    </div><!-- /.card -->

                                    <div class="card card-primary card-outline">
                                        <div class="card-header">
                                            <h5 class="m-0">Featured</h5>
                                        </div>
                                        <div class="card-body">
                                            <h6 class="card-title">Special title treatment</h6>

                                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                            <a href="#" class="btn btn-primary">Go somewhere</a>
                                        </div>
                                    </div><!-- /.card -->
                                </div>
                                <!-- /.col-md-4 -->
                            </div>
                            <!-- /.row -->
                        {% endblock page_content %}
                    </div>
                </div><!-- /.card -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
{% endblock %}


{% block footer %}
    <footer class="main-footer text-sm">
        <small>Theme powered by <a href="https://adminlte.io" target="_blank">AdminLTE.io</a>.</small>
    </footer>
{% endblock footer %}


{% block modals %}
{% endblock modals %}


{% block javascripts_pre %}
    {{ encore_entry_script_tags('app') }}
{% endblock javascripts_pre %}


{% block javascripts %}
    {{ encore_entry_script_tags('omh') }}
{% endblock javascripts %}


{% block javascripts_post %}
    {{ encore_entry_script_tags('zzz') }}
{% endblock javascripts_post %}